# This is the network config written by 'max'
network:
  wifis:
    wlp4s0:
      dhcp4: no
      dhcp6: no
      addresses: [192.168.0.244/24]
      gateway4: 192.168.0.1
      nameservers:
        addresses: [114.114.114.114, 9.9.9.9, 8.8.8.8]
      access-points:
        "max_tp_mesh":
          password: "gwdkpvgj"
  version: 2
