# Generated by Django 4.1.6 on 2023-02-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-title']},
        ),
        migrations.AddField(
            model_name='post',
            name='chapter',
            field=models.CharField(default='ch001', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.CharField(default='beginner', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='project',
            field=models.CharField(default='ue', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(default='001', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
