# Generated by Django 4.1.6 on 2023-02-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_chapter_post_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subject',
            new_name='section',
        ),
    ]
