# Generated by Django 4.1.6 on 2023-02-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_subject_post_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='chapter',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='level',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='project',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(max_length=200),
        ),
    ]
