# Generated by Django 4.1.10 on 2023-10-02 06:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0002_alter_comment_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post",
            new_name="article",
        ),
    ]
